#!/bin/bash

# niri
rm -f ~/.config/niri/config.kdl
mkdir -p ~/.config/niri
stow -t ~ niri

# Noctalia
rm -f ~/.config/noctalia/config.toml
mkdir -p ~/.config/noctalia
stow -t ~ noctalia

# nvim
rm -rf ~/.config/nvim
rm -f ~/.config/nvim
stow -t ~ nvim

# ghostty
rm -f ~/.config/ghostty/config
mkdir -p ~/.config/ghostty
stow -t ~ ghostty

# bashrc
rm -f ~/.bashrc
stow -t ~ bashrc

# fish
rm -f ~/.config/fish/config.fish
mkdir -p ~/.config/fish
stow -t ~ fish
