#!/bin/bash

# niri
rm ~/.config/niri/config.kdl
stow -t ~ niri

# Noctalia
rm -f ~/.config/noctalia/config.toml
stow -t ~ noctalia

# nvim
rm -rf ~/.config/nvim
stow -t ~ nvim

# ghostty
rm -f ~/.config/ghostty/config
stow -t ~ ghostty

# bashrc
rm -f ~/.bashrc
stow -t ~ bashrc

# fish
rm -f ~/.config/fish/config.fish
stow -t ~ fish
