[accessibility]
ui_scale = 1.1000000089406967

[audio]
enable_sounds = true
sound_volume = 0.99999997764825821

[backdrop]
enabled = true

[bar.default]
capsule = true
center = [ "media", "clock", "weather" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "battery", "session" ]
font_family = "Inter"
margin_edge = 4
margin_ends = 4
scale = 1.2000000104308128
start = [ "workspaces", "taskbar" ]
thickness = 40


[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[osd.kinds]
media = false
lock_keys = false
volume_input = false

[shell]
font_family = "Inter"
polkit_agent = true

[shell.screenshot]
confirm_region = true
directory = "/home/humanoid/Pictures/Screenshots"

[theme]
mode = "dark"
source = "wallpaper"

    [theme.templates]
    builtin_ids = [ "cava", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt", "ghostty", "starship" ]
    community_ids = [ "papirus-icons", "obsidian" ]


[wallpaper]
directory = "/home/humanoid/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_seconds = 900

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.media]
hide_album_art = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.clock]
format = "%d %B %H:%M"

[widget.weather]
show_condition = false

[widget.workspaces]
show_labels = false
